name: Release

on:
  push:
    tags:
      - "v*"

  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          # Linux x86_64
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            archive: tar.gz
            binary: send-all-rs

          # Linux ARM64
          - os: ubuntu-latest
            target: aarch64-unknown-linux-musl
            archive: tar.gz
            binary: send-all-rs

          # Windows x86_64
          - os: ubuntu-latest
            target: x86_64-pc-windows-gnu
            archive: zip
            binary: send-all-rs.exe

          # Windows ARM64
          - os: ubuntu-latest
            target: aarch64-pc-windows-gnullvm
            archive: zip
            binary: send-all-rs.exe

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install cross
        run: cargo install cross --git https://github.com/cross-rs/cross

      - name: Build
        run: cross build --release --target ${{ matrix.target }}

      - name: Package
        shell: bash
        run: |
          mkdir release

          cp target/${{ matrix.target }}/release/${{ matrix.binary }} release/

          cd release

          if [[ "${{ matrix.archive }}" == "zip" ]]; then
            7z a ../send-all-rs-${{ matrix.target }}.zip *
          else
            tar czf ../send-all-rs-${{ matrix.target }}.tar.gz *
          fi

      # Always upload build artifacts
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: send-all-rs-${{ matrix.target }}
          path: |
            send-all-rs-*

      # Only create GitHub Releases for tags
      - name: Upload to GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: |
            send-all-rs-*